version: '3.8'

services:
  app:
    build: .
    container_name: spring_kv_app
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/bdKv?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: MyROOTpassword
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: dronkat45@gmail.com
      SPRING_MAIL_PASSWORD: qqme wzui dovw jtnt
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
    restart: always

  db:
    image: mysql:8
    container_name: mysql_kv_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: MyROOTpassword
      MYSQL_DATABASE: bdKv
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always

volumes:
  mysql_data: